Repository kubernetes-csi/volume-data-source-validator, pull requests merged in 2022-04, with the labels that each got.

#29 master: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none

#31 Remove unneeded metadata from CRD
  client/config/crd/populator.storage.k8s.io_volumepopulators.yaml
Labels: kind/bug, lgtm, release-note, cncf-cla: yes, size/XS, approved

#32 Bump image to v1.0.0 in deploy
  deploy/kubernetes/setup-data-source-validator.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, release-note-none
